package ch13;

public class QX10 {

}

// What best describes a reduction?

// A. An intermediate operation where it filters the stream it receives
// B. An intermediate operation where it mathematically divides each element in
// the stream
// C. A terminal operation where a single value is generated by reading each
// element in the prior step in a stream pipeline (+)
// D. A terminal operation where one element is returned from the prior step in
// a stream pipeline without reading all the elements